"""Render a digest dict as the human/LLM-readable markdown twin."""

from .changes import LIFECYCLE, of_digest


def _fmt_count(n: int) -> str:
    return f"{n:,}"


def _fmt_gap(seconds: int) -> str:
    """Minutes while a DBA would still count in minutes, hours after that."""
    if seconds < 7200:
        return f"{seconds // 60} min"
    return f"{seconds / 3600:.1f} h"


def _time_of_day(ts: str) -> str:
    """The clock time of an ISO-8601 stamp. The line already carries the
    group's full timestamp and the change is at most `after_change_hours`
    before it, so the date would only pad the line."""
    return ts.split("T", 1)[-1]


def render_md(d: dict) -> str:
    w = d["window"]
    lines = [
        f"# Digest: {d['db']} — {w['day']}",
        "",
        f"- window: `{w['from']}` → `{w['to']}`",
        f"- events: {_fmt_count(d['totals']['events'])} total, "
        f"{_fmt_count(d['totals']['notable_events'])} notable "
        f"in {d['totals']['notable_groups']} groups",
        f"- notable: **{str(d['notable']).lower()}**",
        f"- generated by: {d['generated_by']}",
        "",
    ]

    if d["deltas"]:
        lines.append("## Deltas (never seen before / anomalies)")
        lines.append("")
        for dl in d["deltas"]:
            t = dl["type"]
            if t == "first_ever_code":
                lines.append(f"- **first-ever error code** `{dl['value']}` "
                             f"({dl['source']}, first seen {dl['first_seen']})")
            elif t == "new_service":
                lines.append(f"- **new listener service** `{dl['value']}`")
            elif t == "new_client_program":
                lines.append(f"- **new client program** `{dl['value']}`")
            elif t == "rate_anomaly":
                lines.append(f"- **rate anomaly** `{dl['counter']}` ({dl['source']}): "
                             f"{_fmt_count(dl['count'])} events in "
                             f"{dl['window_hours']}h ({dl['rate_per_hour']}/h "
                             f"vs baseline median {dl['baseline_median_per_hour']}/h)")
            elif t == "after_change":
                codes = ", ".join(f"`{c}`" for c in dl["codes"])
                head = f"{codes} " if codes else ""
                lines.append(f"- **after a change**: {head}({dl['rule']}, "
                             f"{dl['source']}) first seen {dl['first_ts']}, "
                             f"{_fmt_gap(dl['gap_s'])} after {dl['change_rule']} "
                             f"at {_time_of_day(dl['change_ts'])} — {dl['change']}")
            elif t == "silence":
                lines.append(f"- **silence**: {dl['detail']}")
            else:
                lines.append(f"- {t}: {dl}")
        lines.append("")

    changes = of_digest(d)
    if changes:
        lines.append("## Changes")
        lines.append("")
        for c in changes:
            lines.append(f"- {c.ts} {c.rule} ×{_fmt_count(c.count)} — {c.message}")
        lines.append("")

    for name, s in d["sources"].items():
        lines.append(f"## {name} — {_fmt_count(s['total_events'])} events")
        lines.append("")
        if s["by_class"]:
            bc = ", ".join(f"{k}: {_fmt_count(v)}" for k, v in
                           sorted(s["by_class"].items(), key=lambda kv: -kv[1]))
            lines.append(f"classes: {bc}")
            lines.append("")
        shown = [g for g in s["notable"] if g["class"] != LIFECYCLE]
        if shown:
            lines.append("### Notable")
            lines.append("")
            for g in shown:
                head = f"**[{g['class']}] {g['rule']}** ×{_fmt_count(g['count'])}"
                if g["codes"]:
                    head += " (" + ", ".join(f"`{c}`" for c in g["codes"]) + ")"
                span = g["first_ts"]
                if g["last_ts"] != g["first_ts"]:
                    span += f" → {g['last_ts']}"
                lines.append(f"- {head} — {span}")
                msg = g["message"].strip()
                if msg:
                    for ml in msg.splitlines()[:8]:
                        lines.append(f"  > {ml}")
                ctx = g.get("context")
                if ctx is not None:
                    lines.append("  - context:")
                    for cl in ctx["before"]:
                        lines.append(f"      > [{cl['class']}] {cl['ts']} {cl['message']}")
                    lines.append("      >> this event")
                    for cl in ctx["after"]:
                        lines.append(f"      > [{cl['class']}] {cl['ts']} {cl['message']}")
                ids = ", ".join(f"{s0['index']}/{s0['id']}" for s0 in g["es_samples"][:3])
                if ids:
                    lines.append(f"  - es: {ids}")
            lines.append("")
        if s.get("dropped_notable_groups"):
            events = s.get("dropped_notable_events") or {}
            drops = ", ".join(
                f"{k}: {v}" + (f" ({_fmt_count(events[k])} events)" if k in events else "")
                for k, v in s["dropped_notable_groups"].items())
            lines.append(f"_group cap hit, distinct groups dropped: {drops}_")
            # the codes no shown group carries: without this line a dropped
            # template could hide an ORA code from the reader entirely
            shown_codes = {c for g in s["notable"] for c in g["codes"]}
            hidden = [(c, n) for c, n in (s.get("code_counts") or {}).items()
                      if c not in shown_codes]
            if hidden:
                lines.append("_codes only in dropped groups: " + ", ".join(
                    f"`{c}` ×{_fmt_count(n)}" for c, n in hidden) + "_")
            lines.append("")
        # ahead of the routine counters: build_prompt truncates the tail of
        # this markdown, and counters are the cheaper thing to lose
        if s.get("trace_evidence"):
            lines.append("### Trace evidence")
            lines.append("")
            for e in s["trace_evidence"]:
                rules = ", ".join(e["rules"])
                lines.append(f"- `{e['path']}` — {e['docs_found']} docs, "
                             f"referenced ×{_fmt_count(e['mentions'])} ({rules})")
                for el in e["excerpt"].splitlines():
                    lines.append(f"  > {el}")
                ids = ", ".join(f"{s0['index']}/{s0['id']}"
                                for s0 in e["es_samples"][:3])
                if ids:
                    lines.append(f"  - es: {ids}")
            lines.append("")
        if s["routine_counters"]:
            lines.append("### Routine (counters)")
            lines.append("")
            top = list(s["routine_counters"].items())[:15]
            for k, v in top:
                lines.append(f"- `{k}`: {_fmt_count(v)}")
            rest = len(s["routine_counters"]) - len(top)
            if rest > 0:
                rest_sum = sum(v for _, v in list(s["routine_counters"].items())[15:])
                lines.append(f"- _…{rest} more counters, {_fmt_count(rest_sum)} events_")
            lines.append("")
    return "\n".join(lines) + "\n"
